import type { Metadata } from "next";
import { Playfair_Display, Raleway, JetBrains_Mono } from "next/font/google"; // Changed to Raleway
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"], // Multiple weights
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"], // Multiple weights
});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} ${playfairDisplay.variable} ${jetBrainsMono.variable} antialiased`}
      ><div className="bg-red-50">
        <Navbar />
        <div className="max-w-7xl mx-auto">
          <main>{children}</main>
        </div>
        <Footer />
      </div>
      </body>
    </html>
  );
}
